package com.fomov.kanbanboardbackend.enums;

public enum Position {
	POSITION_BACKEND_DEVELOPER,
	POSITION_FRONTEND_DEVELOPER,
	POSITION_DESIGNER,
	POSITION_BUSINESS_ANALYST,
	POSITION_PROJECT_MANAGER,
	POSITION_PRODUCT_MANAGER,
	POSITION_QA_ENGINEER
}
